apiVersion: v1
kind: Namespace
metadata:
  name: mjbl-api-gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mjbl-kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mjbl-kafka-broker
  template:
    metadata:
      labels:
        app: mjbl-kafka-broker
    spec:
      containers:
      - name: mjbl-kafka-broker
        image: apache/kafka:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
          name: app-port
        resources:
          limits:
            memory: "4Gi"
            cpu: "4000m"
          requests:
            memory: "2Gi"
            cpu: "2000m"
        env:
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://mjbl-kafka-broker-local.mjbl-api-gateway.svc.cluster.local:9092"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@10.101.56.76:9093"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_NUM_PARTITIONS
          value: "3"
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "2000000000"  # 2 GB
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "2000000000"  # 2 GB
        - name: KAFKA_MAX_REQUEST_SIZE
          value: "2000000000"  # 2 GB
---
apiVersion: v1
kind: Service
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-kafka-broker-local
spec:
  selector:
    app: mjbl-kafka-broker
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9092
      targetPort: app-port

---
apiVersion: v1
kind: Service
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-kafka-broker
spec:
  type: NodePort
  selector:
    app: mjbl-kafka-broker
  ports:
    - protocol: TCP
      port: 9092
      targetPort: app-port
      nodePort: 32099

---
apiVersion: v1
kind: Service
metadata:
  namespace: mjbl-api-gateway
  name: mjbl-kafka-broker-lb
spec:
  type: LoadBalancer
  selector:
    app: mjbl-kafka-broker
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP