apiVersion: v1
kind: Namespace
metadata:
  name: spring-boot-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
  namespace: spring-boot-namespace
spec:
  selector:
    matchLabels:
      app: spring-boot
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: spring-boot
          image: 064657201839.dkr.ecr.ap-southeast-1.amazonaws.com/docker-image:latest
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot
  namespace: spring-boot-namespace
spec:
  selector:
    app: spring-boot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-ingress
  namespace: spring-boot-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-boot
                port:
                  number: 6379
