apiVersion: v1
kind: Namespace
metadata:
  name: springboot-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-v1
  namespace: springboot-namespace
spec:
  selector:
    matchLabels:
      app: springboot-app-v1
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-app-v1
    spec:
      containers:
        - name: springboot-app-v1
          image: 064657201839.dkr.ecr.ap-southeast-1.amazonaws.com/docker-image:4dcc4d418a2a75c080ffca28425cbe777f1265c8
          ports:
            - containerPort: 8085
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: ecr-registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: springboot-namespace
spec:
  selector:
    app: springboot-app-v1
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress
  namespace: springboot-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springboot-service
                port:
                  number: 8085
