apiVersion: v1
kind: Namespace
metadata:
  name: springboot-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: springboot-namespace
spec:
  selector:
    matchLabels:
      app: springboot-app
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: 064657201839.dkr.ecr.ap-southeast-1.amazonaws.com/docker-image:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: ecr-registry-secret

---
apiVersion: v1
kind: Service
metadata:
  namespace: springboot-namespace
  name: springboot-app
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
