apiVersion: v1
kind: Namespace
metadata:
  name: database-storage-ns

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-database-pvc
  namespace: database-storage-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-database
  namespace: database-storage-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-database
  template:
    metadata:
      labels:
        app: postgres-database
    spec:
      containers:
      - name: postgres-database
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres-database"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: postgres-database-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-database-storage
        persistentVolumeClaim:
          claimName: postgres-database-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-database-local
  namespace: database-storage-ns
spec:
  type: ClusterIP
  selector:
    app: postgres-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-database
  namespace: database-storage-ns
spec:
  type: NodePort
  selector:
    app: postgres-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: app-port
      nodePort: 32456