apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-storage-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-database
  template:
    metadata:
      labels:
        app: postgres-database
    spec:
      containers:
      - name: postgres-database
        image: postgres-database
        ports:
        - containerPort: 5432
        env:
        - name: postgres-database_PASSWORD
          value: "postgres-database"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: postgres-database-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-database-storage
        persistentVolumeClaim:
          claimName: postgres-database-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-database-service
  namespace: database-storage-ns
spec:
  selector:
    app: postgres-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
